apiVersion: apps/v1
kind: Deployment
metadata:
  name: makemytrip-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: makemytrip
  template:
    metadata:
      labels:
        app: makemytrip
    spec:
      containers:
        - name: makemytrip
          image: erumfaiz/sample:v1
          ports:
            - containerPort: 5000
